import PDFDocument from 'pdfkit'

export function invoicePdf(invoice, items, user) {
  const doc = new PDFDocument({ size: 'A4', margin: 52 })
  const chunks = []
  doc.on('data', (chunk) => chunks.push(chunk))
  const finished = new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))))
  doc.fillColor('#111827').fontSize(22).text('AURORA MOBILITY', { characterSpacing: 2 })
    .fillColor('#64748b').fontSize(9).text('PREMIER DEVICE DISTRIBUTION · TAX INVOICE')
  doc.moveDown(2).fillColor('#111827').fontSize(18).text('INVOICE', { align: 'right' })
    .fontSize(9).fillColor('#64748b').text(invoice.invoice_number, { align: 'right' })
  doc.moveDown().fillColor('#111827').text(`Bill to: ${user.display_name}`, 52).text(user.email)
  doc.moveDown(2)
  doc.fillColor('#64748b').fontSize(9).text('ITEM', 52).text('QTY', 350).text('UNIT', 405).text('TOTAL', 480)
  doc.moveTo(52, doc.y + 5).lineTo(543, doc.y + 5).stroke('#cbd5e1')
  doc.moveDown()
  for (const item of items) { const y = doc.y; doc.fillColor('#111827').fontSize(10).text(item.model, 52, y, { width: 280 }).text(String(item.quantity), 350, y).text(`$${(item.unit_price_cents / 100).toFixed(2)}`, 405, y).text(`$${((item.unit_price_cents * item.quantity) / 100).toFixed(2)}`, 480, y); doc.moveDown() }
  doc.moveDown(2).fillColor('#334155').fontSize(10).text(`Subtotal: $${(invoice.subtotal_cents / 100).toFixed(2)}`, { align: 'right' }).text(`VAT / tax: $${(invoice.tax_cents / 100).toFixed(2)}`, { align: 'right' }).fillColor('#0f172a').fontSize(14).text(`Total: $${(invoice.total_cents / 100).toFixed(2)}`, { align: 'right' })
  doc.moveDown(3).fillColor('#64748b').fontSize(8).text('This document was generated by Aurora Mobility. Device IMEI records are linked to the fulfillment manifest.', { align: 'center' })
  doc.end()
  return finished
}
