import { useEffect, useState } from 'react'
import { Check, Package, Plus, ShieldCheck, Sparkles, Users, X } from 'lucide-react'
import { api } from './lib/api.js'

export default function AdminConsole() {
  const [products, setProducts] = useState([])
  const [users, setUsers] = useState([])
  const [form, setForm] = useState({ sku: 'AUR-NEW-256', brand: 'AURORA', model: 'PHONE Z', storageGb: 256, ramGb: 12, color: 'Obsidian', retailPriceCents: 89900, wholesalePriceCents: 69900 })
  const [message, setMessage] = useState('')
  const refresh = () => Promise.all([api.adminProducts(), api.adminUsers()]).then(([productResult, userResult]) => { setProducts(productResult.products); setUsers(userResult.users) }).catch((error) => setMessage(error.message))
  useEffect(refresh, [])
  async function addProduct(event) { event.preventDefault(); try { await api.createAdminProduct(form); setMessage('Product published to live catalog'); refresh() } catch (error) { setMessage(error.message) } }
  async function approve(id) { await api.updateAdminUser(id, { verified: true, role: 'reseller' }); refresh() }
  return <main className="admin-screen"><header className="admin-header"><div className="retail-logo"><div className="brand-mark"><Sparkles size={15} /></div>AURORA <span>OPERATIONS</span></div><div className="admin-status"><ShieldCheck size={15} /> Super Admin console</div></header><div className="admin-content"><div className="eyebrow gold-text">DISTRIBUTOR COMMAND CENTER · LIVE</div><h1>Control the ecosystem.</h1><p className="admin-lede">Manage catalog, pricing, image assets, and partner access from one secure surface.</p><div className="admin-grid"><section className="admin-card glass"><div className="admin-card-head"><div><h2><Package size={16} /> Product catalog</h2><small>{products.length} live SKUs · multi-tier pricing enabled</small></div><button className="icon-button"><Plus size={17} /></button></div><form className="product-form" onSubmit={addProduct}><input placeholder="SKU" value={form.sku} onChange={(e) => setForm({ ...form, sku: e.target.value })} /><input placeholder="Brand" value={form.brand} onChange={(e) => setForm({ ...form, brand: e.target.value })} /><input placeholder="Model" value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} /><input placeholder="Color" value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /><input type="number" placeholder="Retail cents" value={form.retailPriceCents} onChange={(e) => setForm({ ...form, retailPriceCents: Number(e.target.value) })} /><input type="number" placeholder="Wholesale cents" value={form.wholesalePriceCents} onChange={(e) => setForm({ ...form, wholesalePriceCents: Number(e.target.value) })} /><button className="primary-btn" type="submit">Publish new model <Plus size={14} /></button></form><div className="admin-product-list">{products.slice(0, 5).map((product) => <div key={product.id}><span><b>{product.sku}</b><small>{product.brand} {product.model} · {product.available_stock} available</small></span><strong>${(product.wholesale_price_cents / 100).toLocaleString()}</strong></div>)}</div></section><section className="admin-card glass"><div className="admin-card-head"><div><h2><Users size={16} /> Partner approvals</h2><small>Verification and commission access</small></div><span className="admin-count">{users.filter((user) => !user.verified_at).length} pending</span></div><div className="admin-user-list">{users.map((user) => <div key={user.id} className="admin-user"><div className="avatar">{user.display_name.slice(0, 2).toUpperCase()}</div><span><b>{user.display_name}</b><small>{user.email} · Tier {user.commission_tier}</small></span>{user.verified_at ? <span className="verified"><Check size={12} /> Verified</span> : <button className="approve-btn" onClick={() => approve(user.id)}>Approve</button>}</div>)}</div></section></div>{message && <div className="admin-toast">{message}<button onClick={() => setMessage('')}><X size={13} /></button></div>}</div></main>
}
